theme: jekyll-theme-minimal

title: [Daniel Tzu Shiuan Chen]
description: [oh, so apparently, I don't need the brackets.]
description: [and.... that's not true. Let's try adding a logo!]

logo: [840726E2-9286-48CA-AA12-96E894288209.jpeg]
